apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginxhello-hr
  namespace: default
  annotations:
    fluxcd.io/ignore: "true"
spec:
  chart:
    git: ssh://git@github.com:rozdolsky33/gitops-nginxhello.git
    path: helm/chart
    ref: master
  rollback:
    enable: true
    retry: true
